### ISSUE TITLE
Move card data out of repo

### ISSUE THREAD

**Issue by danj3000** [danj3000/ashteki#16]
Use a fetch data script similar to keyteki/ringteki to get data on server

Should this be a straight download from ashes.live?

**Comment by onecrayon** [comment]
Very likely; you can find API documentation here: https://api.ashes.live

The endpoint you're looking for is `v2/cards`. Data from that endpoint is mostly stable at this point, though I will likely be modifying the output for conjurations to include all possible conjurations in the chain (instead of just conjurations that apply to that particular card). Currently it's outputting everything through Astrea/Koji, and I'll be opening up the other releases as I get the images prepped.

**Comment by danj3000** [comment]
The cards API doesn't want to send me all the data at once. If the limit number is too high it will error 500. I have updated the data manually today by stitching together as a temp workaround

**Comment by onecrayon** [comment]
@danj3000 Hm, it shouldn't throw a 500; I'll look into that. However, it does have a hard upper limit of 100 records per request at the moment. If you need to load in the full card set all at once, you can do something like this pseudocode:

```
next = 'https://api.ashes.live/v2/cards'
cards = []
while (next) {
  data = ajaxLibrary.get(next)
  cards += data.results
  next = data.next
}
```

**Comment by danj3000** [comment]
closing this - storing locally in the repo, but will consider ashes.live master.
