### ISSUE TITLE
Summon Shadow Hound Book

### ISSUE THREAD

**Issue by ShuffleBusJesse** [danj3000/ashteki#233]
Shadow Hound Book doesn't trigger the focus effect of deal 1 damage than deal 1 damage when summoned and two hounds are on the Battlefield.

**Comment by danj3000** [comment]
Hey Jesse, thanks for creating these issues.

SummonShadowHound (like SummonGilder and other similar multi-action cards) uses a structure like this:
```
target: {
    // summon conjuration
},
then: {
    // do additional stuff
}
```
The framework makes the 'then' clause dependent upon the first 'target' clause successful resolution. To make the 'then' clause happen regardless, it needs an attribute like so:
```
then: {
    alwaysTriggers: true,
    // do additional stuff
}

```
a small fix that I often miss first time round :D
_(just talking this through in order to create some dev notes)_

**Comment by ShuffleBusJesse** [comment]
No problem... just wanted to let you know. that the focus effect, like on gilder, is independent of whether the conjuration actually gets summoned.
