### ISSUE TITLE
auto-pin power dice at end of round

### ISSUE THREAD

**Issue by bdwain** [danj3000/ashteki#502]
it's easy to forget. It might make sense to have an intrusive modal show up to force you to choose the dice to keep (since that's kind of how it works in person), but as a start, auto-pinning power dice should be simpler and accomplish most of the goal

**Comment by danj3000** [comment]
Agreed, I like this idea.On 4 Jun 2021 19:20, Bryan Wain ***@***.***> wrote:
it's easy to forget. It might make sense to have an intrusive modal show up to force you to choose the dice to keep (since that's kind of how it works in person), but as a start, auto-pinning power dice should be simpler and accomplish most of the goal
