### ISSUE TITLE
summon turtle guard should require you to exhuast a turtle

### ISSUE THREAD

**Issue by bdwain** [danj3000/ashteki#542]
summon turtle guard let someone with a no turtle guards on their battlefield exhaust a unit. it should require you to exhaust your own turtle to do that.

**Comment by danj3000** [comment]
I can't reproduce this bug. if you see it again can you capture a screenshot, or steps to reproduce?

**Comment by bdwain** [comment]
If it helps, I had an undxhausted unit on my battlefield and they had a
full battlefield with all exhausted units, none of them turtles. And they
were still able to exhaust my unit

**Comment by 5H4Z** [comment]
I was able to reproduce this one. Essentially, when I select Focus Without Summon, when I have no Turtle Guards in play, getTurtleTargets skips over the choosing an unexhausted Turtle Guard to exhaust and just lets me exhaust an opposing unit.

**Comment by danj3000** [comment]
The 2 buttons are a workaround. The issue is to investigate whether it can be done using just one. Low priority and probably hard to resolve.On 3 Sep 2021 23:24, 5H4Z ***@***.***> wrote:
I was able to reproduce this one. Essentially, when I select Focus Without Summon, when I have no Turtle Guards in play, getTurtleTargets skips over the choosing an unexhausted Turtle Guard to exhaust and just lets me exhaust an opposing unit.

**Comment by 5H4Z** [comment]
I fixed this one as part of #654 - the option Focus without Summon is only available if you have an unexhausted Turtle Guard in play and the book is focussed.
